apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch-operator
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: openshift-operators-redhat
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: elasticsearch-operator
    repoURL: {{ .Values.spec.source.repoURL }}
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
