apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: servicemeshoperator
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: openshift-operators
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: servicemeshoperator
    repoURL: {{ .Values.spec.source.repoURL }}
