apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: servicemeshoperator
  namespace: openshift-gitops
spec:
  destination:
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: servicemeshoperator
    repoURL: {{ .Values.spec.source.repoURL }}
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
