apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: smcp
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: istio-system
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: smcp
    repoURL: {{ .Values.spec.source.repoURL }}
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
